Kc 22 google account login
Capstone-Projects-2022-Spring/project-keyctrl pull request #21
Opened 2022-03-08 22:16 UTC by tuh26781

Signup and login works

2022-03-08 23:10 UTC, jclamanna reviewed
worked on and tested together, looks good

2022-03-08 23:10 UTC, jclamanna approved these changes

2022-03-09 00:04 UTC, ColinHarker requested changes
Needs to be merged into `develop` not `main`

2022-03-09 03:19 UTC, ColinHarker approved these changes

2022-03-09 20:42 UTC, merged